### ISSUE TITLE
Remove hard-coding of `program` and `project` name from sanitizer

### ISSUE THREAD

**Issue by mikebaumann** [DataBiosphere/newt-transformer#26]
The sanitizer (`data_bleach.py`) will soon be used on data for multiple projects and must not hard-code the `program` and `project` name as it does now.

┆Issue is synchronized with this [JIRA Task](https://ucsc-cgl.atlassian.net/browse/NEWT-24)
┆Project Name: CGP-Newt
┆Issue Number: NEWT-24

**Comment by jessebrennan** [comment]
Not sure when it happened, but this has been fixed.
